# Generated by Django 2.1.3 on 2018-11-19 08:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_date', models.DateField(unique=True, verbose_name='Datum')),
                ('reg_overtime', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Überstunden')),
                ('adj_overtime', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Überstunden')),
                ('user_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=10, verbose_name='Projektcode')),
                ('project_description', models.CharField(default='', max_length=100, verbose_name='Projektbeschreibung')),
                ('employer', models.CharField(choices=[('KEINE', 'Keine'), ('AVGL', 'Avantgarde-labs'), ('CE', 'Conrad')], default='KEINE', max_length=20, verbose_name='Schnittstelle')),
                ('user_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(default=datetime.date(2018, 1, 1), verbose_name='Startdatum')),
                ('work_time_mon', models.DecimalField(decimal_places=2, default=8, max_digits=10, verbose_name='Arbeitszeit Montag')),
                ('work_time_tue', models.DecimalField(decimal_places=2, default=8, max_digits=10, verbose_name='Arbeitszeit Dienstag')),
                ('work_time_wed', models.DecimalField(decimal_places=2, default=8, max_digits=10, verbose_name='Arbeitszeit Mittwoch')),
                ('work_time_thu', models.DecimalField(decimal_places=2, default=8, max_digits=10, verbose_name='Arbeitszeit Donnerstag')),
                ('work_time_fri', models.DecimalField(decimal_places=2, default=8, max_digits=10, verbose_name='Arbeitszeit Freitag')),
                ('work_time_sat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Arbeitszeit Samstag')),
                ('work_time_sun', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Arbeitszeit Sonntag')),
                ('user_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('description', models.CharField(default='', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=250)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracking.Project')),
                ('user_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
