# Generated by Django 2.1.2 on 2018-10-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_entry',
            name='created_by',
            field=models.CharField(max_length=250),
        ),
    ]
