# Generated by Django 2.1.1 on 2018-11-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0004_auto_20181104_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_entry',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracking.Project'),
        ),
    ]
