# Generated by Django 2.1.1 on 2018-11-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0005_auto_20181104_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employer',
            field=models.CharField(choices=[('AVGL', 'Avantgarde-labs'), ('CE', 'Conrade')], default='AVGL', max_length=20),
        ),
    ]
