# Generated by Django 2.1.1 on 2018-11-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0006_project_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employer',
            field=models.CharField(choices=[('AVGL', 'Avantgarde-labs'), ('CE', 'Conrad')], default='AVGL', max_length=20),
        ),
    ]
