# Generated by Django 2.1.1 on 2018-11-04 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_tracking', '0007_auto_20181104_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_date', models.DateField(verbose_name='Datum')),
                ('overtime', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Überstunden')),
                ('type', models.CharField(choices=[('reg', 'regular'), ('adj', 'adjustment')], default='adj', max_length=3, verbose_name='Typ')),
                ('user_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('work_time_mon', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Arbeitszeit Montag')),
                ('work_time_tur', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Arbeitszeit Dienstag')),
                ('work_time_wed', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Arbeitszeit Mittwoch')),
                ('work_time_thu', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Arbeitszeit Donnerstag')),
                ('work_time_fri', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Arbeitszeit Freitag')),
                ('work_time_sat', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Arbeitszeit Samstag')),
                ('work_time_sun', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Arbeitszeit Sonntag')),
                ('user_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Overtime_Adjustment_Entry',
        ),
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='employer',
            field=models.CharField(choices=[('AVGL', 'Avantgarde-labs'), ('CE', 'Conrad')], default='AVGL', max_length=20, verbose_name='Arbeitgeber'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Projektcode'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(default='', max_length=100, verbose_name='Projektbeschreibung'),
        ),
        migrations.AlterField(
            model_name='time_entry',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
