# Generated by Django 2.1.1 on 2018-11-04 20:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_tracking', '0008_auto_20181104_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='SettingsModel',
        ),
    ]
