# Generated by Django 2.1.1 on 2018-11-11 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0010_auto_20181111_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 1, 1), verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='work_time_fri',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=10, verbose_name='Arbeitszeit Freitag'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='work_time_mon',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=10, verbose_name='Arbeitszeit Montag'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='work_time_sat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Arbeitszeit Samstag'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='work_time_sun',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Arbeitszeit Sonntag'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='work_time_thu',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=10, verbose_name='Arbeitszeit Donnerstag'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='work_time_tue',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=10, verbose_name='Arbeitszeit Dienstag'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='work_time_wed',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=10, verbose_name='Arbeitszeit Mittwoch'),
        ),
    ]
