# Generated by Django 2.1.1 on 2018-11-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0011_auto_20181111_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime_entry',
            name='adj_overtime',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Überstunden'),
        ),
    ]
